language: node_js
node_js:
  - 8.12.0
sudo: required
services:
  - docker
env:
  global:
    - CXX=g++-4.8
  matrix:
    - USE_SENTRY=1

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - docker pull getsentry/sentry-cli

script:
  - npm install
  - NODE_ENV=production npm run build:dll
  - npm run build

before_deploy:
  - bash deploy/sentry_release.sh
  - find dist/ -type f -name "*.map" -delete
  - zip -r dist.zip dist

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: qCdjztXiMKDxfRnD2GYnJuducjnB7NzCEwssJdyFrvlGEzRbguLhsFJ0JKLg9ra3lKU0OmOgBsBGgoQGKYZV4vXGt55XizgT6Nu7Nh0YxM1xMsv5ZLnG4zn21J2JrFhmDQs/z6fr/Um6cAdfchxx04YJmfNVPXkClonq4zvESpb+4nHSGDKpHEL2U82R0ruW5pSIPC7d69XP3OrhQKdIpzabkpZyfnZe5bGUl6XawHrik7Ra22QBtjqWzCfRkX3eCFdsHjIYiOtwOtlyX6Yv/Mu2P0wnbdsSWOcp3BnD3tuUvxF2W+T5FugNT1RfHvkNn6xaANCel9Ve2ESBvzUNtKBTZ8eG9IfZ4aS5/uBJbazU069nj7jckHMCZtXr9P2GX9QqxKdsJePeo7EXA3jKeAlhv0nM4cSNtRmWCMVrzyJYnqjswlejHKxclgOy9AiCmw/sF1HX+IFGl84bS1JYWP6VgjQ0gWkVGsS5xpktQVYNE/FaYqUu1oQ3J0e0m+i8V4zHAPY+hyrCW+Vpy0G1xU3YYoIY5nm3b1DiuqE1lH7pWzTcQBOihfe8gsvHrkTmS6XFwRNXZvfdLe+cj2IM2N4q1zNjX+z9RddjKjFLRseDVnMnKCxJB0yGqmTlCD98MCt+O/a8VbmzM+0RzrqzKWSoRKlCQ9lnTOgaJvXxWAg=
  file: dist.zip
  on:
    repo: Harry-zklcdc/OJ
    all_branches: true
    tags: true
